services:
  web:
    image: egortensin/wg-api-web:1
    depends_on: [api]
    restart: unless-stopped
    ports:
      - '8090:80'
    volumes:
      - './data:/data:ro'
  api:
    # The upstream image doesn't use tags (as of April '26), just hashes, so
    # we're pinning to latest.
    image: james/wg-api
    command: wg-api --device "${WG_IFACE:-wg0}" --listen 192.168.177.1:1234
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        # The network is hardcoded; please don't change. If you run into
        # problems, let me know.
        - subnet: 192.168.177.0/24
