version: '3'

services:
  web:
    image: egortensin/wg-api-web:1
    depends_on: [api]
    restart: unless-stopped
    ports:
      - '8090:80'
    volumes:
      - './data:/data:ro'
  api:
    # Pin to 'latest' or to a different hash if running on something other than
    # x64. The hash was used because the upstream image doesn't use versions
    # (as of Jan 2023).
    image: james/wg-api@sha256:76428f4fe0efee9e0d17c8d89920535d536675f604a9f5081075615cac0d2411
    command: wg-api --device "${WG_IFACE:-wg0}" --listen 192.168.177.1:1234
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.177.0/24
