name: CI

on:
  push:
  schedule:
    # The time of 02:30 on Fridays was chosen somewhat randomly. The reason for
    # this even existing is the fact that the wg-api image is not pinned to a
    # specific version currently. If it gets pinned, this can be removed.
    - cron: '30 02 * * 5'
  workflow_dispatch:

jobs:
  test_host:
    runs-on: ubuntu-latest
    name: Test (host)
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install dependencies
        run: sudo apt install -y wireguard-tools
      - name: Test
        run: sudo ./test/host/test.sh

  test_linuxserver:
    runs-on: ubuntu-latest
    name: Test (LinuxServer)
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test
        run: sudo ./test/linuxserver/test.sh

  publish:
    needs: [test_host, test_linuxserver]
    runs-on: ubuntu-latest
    name: 'Publish'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # https://github.com/docker/metadata-action#semver
      - id: meta
        name: Docker Hub metadata
        uses: docker/metadata-action@v6
        with:
          images: egortensin/wg-api-web
          flavor: |
            latest=auto
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Push? Which platforms?
        id: params
        # Building for ARM for every commit in master is too time-consuming.
        run: |
          if ${{ github.ref == 'refs/heads/master' }}; then
              echo 'push=true' >> "$GITHUB_OUTPUT"
              echo 'platforms=amd64' >> "$GITHUB_OUTPUT"
          elif ${{ startsWith(github.ref, 'refs/tags/') }}; then
              echo 'push=true' >> "$GITHUB_OUTPUT"
              echo 'platforms=amd64,armhf,arm64' >> "$GITHUB_OUTPUT"
          else
              echo 'push=false' >> "$GITHUB_OUTPUT"
              echo 'platforms=amd64' >> "$GITHUB_OUTPUT"
          fi
      - name: Login to Docker Hub
        # https://github.com/orgs/community/discussions/163013
        if: steps.params.outputs.push == 'true'
        uses: docker/login-action@v4
        with:
          username: egortensin
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: Build and publish
        uses: docker/build-push-action@v7
        with:
          # Without context, .dockerignore isn't respected?
          # https://stackoverflow.com/a/74552407/514684
          context: .
          labels: '${{ steps.meta.outputs.labels }}'
          platforms: '${{ steps.params.outputs.platforms }}'
          push: '${{ steps.params.outputs.push }}'
          tags: '${{ steps.meta.outputs.tags }}'
